import { describe, expect, it } from 'vitest';
import { buildMap, findUniqueAntinodes } from './findAntinodes';

const INPUT = `
	............
	........0...
	.....0......
	.......0....
	....0.......
	......A.....
	............
	............
	........A...
	.........A..
	............
	............`;

describe('day08 : findAntinodes', () => {
	it('finds all antinodes for a signal map', () => {
		const signalMap = buildMap(INPUT);
		expect(findUniqueAntinodes(signalMap)).toHaveLength(14);
	});
});
